name: Deploy to Vercel

on:
  workflow_call:
    inputs:
      is-prod:
        required: true
        type: string
        description: "True to deploy to Vercel Production, false for Vercel Preview"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        id: deploy-vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: ${{ inputs.is-prod == 'true' && '--prod' || '' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Deployment URL to Job Summary
        run: |
          echo "### Vercel Deployment Successful! 🚀" >> $GITHUB_STEP_SUMMARY
          echo "- **Target Environment**: ${{ inputs.is-prod == 'true' && 'Production' || 'Preview/Staging' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Deployment URL**: ${{ steps.deploy-vercel.outputs.vercel-url }}" >> $GITHUB_STEP_SUMMARY
